// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtrCuMlu1-wUhi_fa1ZyChHTjcgJHLGzE',
    appId: '1:420874539247:web:26ab941a6c0c04bdea4b1a',
    messagingSenderId: '420874539247',
    projectId: 'shopping-app-5e7f5',
    authDomain: 'shopping-app-5e7f5.firebaseapp.com',
    storageBucket: 'shopping-app-5e7f5.firebasestorage.app',
    measurementId: 'G-L3B2J201ZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1WKiwTGpd_OmR6m8Et1PWszI-fR2ccq0',
    appId: '1:420874539247:android:2409a9dd5b89f2d7ea4b1a',
    messagingSenderId: '420874539247',
    projectId: 'shopping-app-5e7f5',
    storageBucket: 'shopping-app-5e7f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsejp2x99Fx0mwyoLsOUjxTo4qQWsjp2Q',
    appId: '1:420874539247:ios:2753f790ba0fe072ea4b1a',
    messagingSenderId: '420874539247',
    projectId: 'shopping-app-5e7f5',
    storageBucket: 'shopping-app-5e7f5.firebasestorage.app',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsejp2x99Fx0mwyoLsOUjxTo4qQWsjp2Q',
    appId: '1:420874539247:ios:2753f790ba0fe072ea4b1a',
    messagingSenderId: '420874539247',
    projectId: 'shopping-app-5e7f5',
    storageBucket: 'shopping-app-5e7f5.firebasestorage.app',
    iosBundleId: 'com.example.project1',
  );
}
